server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service # 动态路由匹配
#          uri: http://localhost:8081   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://cloud-payment-service
#          uri: http://localhost:8081
          filters:
            - AddRequestParameter=X-Request-id,1024 # Filter会在匹配上的请求的请求头上加上X-Request-id的值1024
          predicates:
            - Path=/payment/lb  #断言,路径相匹配的进行路由
#            - After=2020-05-13T13:53:21.993+08:00[Asia/Shanghai] #  在指定时间之前访问此URL不起作用
#            - Cookie=username,danbro # 此URI需要携带Cookie才能成功访问


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/ # Eureka单机
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: cloud-gateway-service