server:
  port: 2100

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group # 在 seata 的 file.conf配置文件中自定义的事务组名
    nacos:
      server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seat_order?relaxAutoCommit=true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
