server:
  port: 2103

spring:
  application:
    name: seata-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group # 在 seata 的 file.conf配置文件中自定义的事务组名
    nacos:
      server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seat_storage?relaxAutoCommit=true
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
