server:
  port: 9002

spring:
  application:
    name: payment-service-nacos # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:3333 # nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"