server:
  port: 9100

spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos 地址和端口
    sentinel:
      transport:
        dashboard: localhost:8080 # 配置 DashBoard 的ip和端口
        port: 8719 # 默认8719 Sentinel 监控服务的端口 如果被占用会在原来的端口号上加1，直到端口没有被占用
      datasource: # 配置数据源 实现Sentinel规则的持久化
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rule
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow # 规则类型

management:
  endpoints:
    web:
      exposure:
        include: "*"
