server:
  port: 8081 # 服务端口号
spring:
  application:
    name: Cloud-Payment-Service # 服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db2019?relaxAutoCommit=true
eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/ # Eureka集群
      defaultZone: http://eureka7001:7001/eureka/ # Eureka单机
    fetch-registry: true # 是否从EurekaServer抓取已有的注册消息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡。
    register-with-eureka: true # 表示自己是否注册进eureka注册中心
  instance:
    instance-id: payment-8081 # 在Eureka注册中心显示id，不显示hostname和端口
    prefer-ip-address: true # 当把鼠标放到instance-id上显示主机ip
    lease-renewal-interval-in-seconds: 1 # 发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 2 # Eureka服务端上一次接收到心跳的时间间隔，超时将被剔除服务。