server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
    register-with-eureka: false # 不在Eureka注册
logging:
  level:
    com.danbro.springcloud.service.PaymentFeignService: debug
